#!/bin/sh /etc/rc.common
START=90
STOP=10

USE_PROCD=1
PROG=/usr/bin/edge
CONFIGFILE=/etc/config/n2n-edge.conf

section_enable() {
	config_get_bool enable "$1" enable 0
	[ $enable -gt 0 ]
}

edge() {
	section_enable "$section" || return 1
	procd_open_instance
	procd_set_param command $PROG $CONFIGFILE
	procd_set_param file $CONFIGFILE
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	config_load 'n2n'
	config_foreach edge 'base'
}

stop_service()
{
	service_stop $PROG
}

service_triggers()
{
	procd_add_reload_trigger "n2n"
}
