#!/bin/sh /etc/rc.common
START=90
STOP=10

USE_PROCD=1
PROG=/usr/bin/supernode
CONFIGFILE=/etc/n2n/supernode.conf

section_enabled() {
	config_get_bool enabled "$1" enabled 0
	[ $enabled -gt 0 ]
}

supernode() {
	section_enabled "$section" || return 1
	procd_open_instance
	procd_set_param command $PROG $CONFIGFILE
	procd_set_param file $CONFIGFILE
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	config_load 'n2n'
	config_foreach supernode 'base'
}

stop_service()
{
	service_stop $PROG
}

service_triggers()
{
	procd_add_reload_trigger "n2n"
}
