#!/bin/sh /etc/rc.common
# Copyright (C) 2011-2014 OpenWrt.org

START=90
STOP=10

USE_PROCD=1
PROG=/usr/bin/rsync

section_enabled() {
	config_get_bool enabled "$1" enabled 0
	[ $enabled -gt 0 ]
}

rs() {
	section_enabled "$section" || return 1
	procd_open_instance
	procd_set_param command "$PROG" --daemon --no-detach
	procd_close_instance
}

start_service() {
	config_load 'rsyncd'
	config_foreach rs 'base'
}

service_triggers()
{
	procd_add_reload_trigger "rsyncd"
}
